"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import type { SVGProps } from "react";

/**
 * Why Choose Us — homepage section.
 * Follows the design tokens defined in globals.css (colors, radius, shadow,
 * spacing, type scale) via the Tailwind utilities generated by the
 * `@theme inline` block. globals.css itself is not modified.
 */

function ShieldIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} {...props}>
      <path
        d="M12 3.5l7 2.6v5.2c0 4.6-3 8.2-7 9.2-4-1-7-4.6-7-9.2V6.1l7-2.6Z"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path d="M9 12.2l2.1 2.1L15.3 10" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function TechnicianIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} {...props}>
      <circle cx="12" cy="7.5" r="3.25" />
      <path d="M4.75 20c.9-3.6 3.8-5.75 7.25-5.75S18.35 16.4 19.25 20" strokeLinecap="round" />
      <path d="M9 8.25l2 1.75 4-3.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function ResponseIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} {...props}>
      <circle cx="12" cy="12" r="8.25" />
      <path d="M12 7.5V12l3 2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function PriceIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} {...props}>
      <circle cx="12" cy="12" r="8.25" />
      <path d="M9.75 15c0 1.1 1 2 2.25 2s2.25-.7 2.25-1.75c0-2.5-4.5-1.5-4.5-4C9.75 9.7 10.75 9 12 9s2.25.9 2.25 2" strokeLinecap="round" />
      <path d="M12 7.75v.6M12 15.6v.65" strokeLinecap="round" />
    </svg>
  );
}

const benefits = [
  {
    title: "Expert Technicians",
    description:
      "Every job is carried out by fully trained, licensed technicians who identify the pest, the cause, and the right treatment for it — not a one-size-fits-all spray.",
    icon: TechnicianIcon,
  },
  {
    title: "Fast Response Service",
    description:
      "Pest problems rarely wait for a convenient time. We offer fast callouts and emergency availability so an infestation gets treated before it has a chance to spread.",
    icon: ResponseIcon,
  },
  {
    title: "Affordable Pricing",
    description:
      "Clear, upfront pricing with no hidden call-out fees, so you know exactly what a treatment costs before any work begins.",
    icon: PriceIcon,
  },
];

const containerVariants = {
  hidden: {},
  show: {
    transition: { staggerChildren: 0.12, delayChildren: 0.1 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 18 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: [0.22, 1, 0.36, 1] } },
};

export default function WhyChooseUs() {
  return (
    <section className="relative overflow-hidden py-section px-page">
      {/* decorative background shape — purely visual, kept subtle */}
      <svg
        aria-hidden="true"
        viewBox="0 0 400 400"
        className="pointer-events-none absolute -right-32 top-0 -z-10 hidden h-[32rem] w-[32rem] text-brand-purple/[0.05] lg:block"
      >
        <circle cx="200" cy="200" r="200" fill="currentColor" />
      </svg>

      <div className="mx-auto grid max-w-content items-center gap-12 lg:grid-cols-[minmax(0,0.92fr)_minmax(0,1.08fr)] lg:gap-16">
        {/* Image column */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.3 }}
          transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
          className="relative"
        >
          <div className="relative aspect-[5/4] w-full overflow-hidden rounded-xl shadow-raised sm:aspect-[4/3] lg:aspect-[4/5]">
            <Image
              src="https://images.unsplash.com/photo-1687840936382-7333b7d26fca?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="Pest control technician inspecting a property in London"
              fill
              sizes="(min-width: 1024px) 46vw, 100vw"
              className="object-cover"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-brand-navy-deep/60 via-transparent to-transparent" />
          </div>

          {/* Floating info card */}
          <div className="absolute -bottom-6 left-5 right-5 flex items-center gap-3 rounded-lg border border-border bg-surface p-4 shadow-card sm:right-auto sm:w-64">
            <span className="grid h-11 w-11 flex-none place-items-center rounded-md bg-surface-muted text-brand-purple">
              <ShieldIcon className="h-5 w-5" />
            </span>
            <div>
              <p className="font-display text-sm font-bold leading-tight text-brand-navy">
                Fully Trained Team
              </p>
              <p className="text-xs leading-tight text-text-secondary">
                Licensed &amp; insured technicians
              </p>
            </div>
          </div>
        </motion.div>

        {/* Content column */}
        <div className="pt-8 lg:pt-0">
          <span className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.09em] text-brand-purple-strong">
            <span className="h-2 w-2 rounded-pill bg-brand-red" aria-hidden="true" />
            Why Choose Us
          </span>

          <h2 className="mt-4 max-w-[14ch] font-display text-heading-xl font-bold leading-[1.05] tracking-tight text-brand-navy">
            Trusted Pest Control Experts In London
          </h2>

          <p className="mt-4 max-w-[42ch] text-text-secondary">
            We deal with the problem properly, not just the symptoms — professional
            treatment from trained technicians, backed by fast response times and
            pricing you can trust from the first call.
          </p>

          <motion.div
            variants={containerVariants}
            initial="hidden"
            whileInView="show"
            viewport={{ once: true, amount: 0.2 }}
            className="mt-8 grid gap-4"
          >
            {benefits.map((benefit) => (
              <motion.div
                key={benefit.title}
                variants={itemVariants}
                className="flex gap-4 rounded-lg border border-border bg-surface p-5 shadow-soft transition-shadow duration-200 hover:shadow-card"
              >
                <span className="grid h-12 w-12 flex-none place-items-center rounded-md bg-surface-muted text-brand-purple">
                  <benefit.icon className="h-6 w-6" />
                </span>
                <div>
                  <h3 className="font-display text-lg font-bold text-brand-navy">
                    {benefit.title}
                  </h3>
                  <p className="mt-1 text-sm leading-relaxed text-text-secondary">
                    {benefit.description}
                  </p>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </div>
    </section>
  );
}